import express from 'express';
import { authenticate, requirePermission } from '../middleware/auth.js';
import { asyncHandler, ApiError } from '../utils/errors.js';
import { recordAudit } from '../utils/audit.js';
import { now } from '../utils/ids.js';
import { appStore, findOne, insert, regex, update, count } from '../db/app-store.js';
import { assert, requireFields, toBool, toNumber, paginate, isEmail } from '../utils/validate.js';
const router = express.Router(); router.use(authenticate);
async function enrich(doctor) { const { collections } = await appStore(); const patients = await collections.patients.countDocuments({ referred_by: doctor.id, is_deleted: 0 }); const orders = await collections.orders.find({ doctor_id: doctor.id, is_deleted: 0 }).toArray(); return { ...doctor, patient_count: patients, order_count: orders.length, referred_revenue: orders.reduce((s, o) => s + Number(o.total || 0), 0) }; }
function validate(body) { if (body.email) assert(isEmail(body.email), 'Email address is not valid'); if (body.commission_percent !== undefined) assert(toNumber(body.commission_percent, 0) >= 0 && toNumber(body.commission_percent, 0) <= 100, 'Commission must be between 0 and 100'); }
router.get('/', requirePermission('doctors.view', 'patients.view'), asyncHandler(async (req, res) => { const { page, limit, offset } = paginate(req.query); const filter = {}; if (req.query.search) { const r = regex(req.query.search); filter.$or = [{ name: r }, { specialization: r }, { hospital: r }, { phone: r }]; } if (req.query.active === 'true') filter.is_active = 1; const { collections } = await appStore(); const total = await collections.doctors.countDocuments(filter); const rows = await collections.doctors.find(filter).sort({ name: 1 }).skip(offset).limit(limit).toArray(); res.json({ data: await Promise.all(rows.map(enrich)), meta: { total, page, limit, pages: Math.ceil(total / limit) || 1 } }); }));
router.get('/options', requirePermission('doctors.view', 'patients.view', 'orders.view', 'orders.create'), asyncHandler(async (req, res) => { const { collections } = await appStore(); res.json({ data: await collections.doctors.find({ is_active: 1 }, { projection: { id: 1, name: 1, specialization: 1, hospital: 1 } }).sort({ name: 1 }).toArray() }); }));
router.get('/:id', requirePermission('doctors.view'), asyncHandler(async (req, res) => { const doctor = await findOne('doctors', { id: Number(req.params.id) }); if (!doctor) throw ApiError.notFound('Doctor not found'); const { collections } = await appStore(); const recent = await collections.patients.find({ referred_by: doctor.id, is_deleted: 0 }, { projection: { id: 1, patient_code: 1, full_name: 1, created_at: 1 } }).sort({ created_at: -1 }).limit(10).toArray(); res.json({ data: { ...(await enrich(doctor)), recent_patients: recent } }); }));
router.post('/', requirePermission('doctors.create'), asyncHandler(async (req, res) => { requireFields(req.body, ['name']); validate(req.body); const timestamp = now(); const doctor = await insert('doctors', { name: String(req.body.name).trim(), qualification: req.body.qualification || null, specialization: req.body.specialization || null, hospital: req.body.hospital || null, phone: req.body.phone || null, email: req.body.email || null, address: req.body.address || null, commission_percent: toNumber(req.body.commission_percent, 0), notes: req.body.notes || null, is_active: toBool(req.body.is_active, true) ? 1 : 0, created_by: req.user.id, created_at: timestamp, updated_at: timestamp }); await recordAudit({ req, action: 'create', module: 'doctors', entity: 'doctor', entityId: doctor.id, description: `Added doctor "${doctor.name}"` }); res.status(201).json({ data: await enrich(doctor) }); }));
router.put('/:id', requirePermission('doctors.edit'), asyncHandler(async (req, res) => { const id = Number(req.params.id); const existing = await findOne('doctors', { id }); if (!existing) throw ApiError.notFound('Doctor not found'); requireFields(req.body, ['name']); validate(req.body); const value = { name: String(req.body.name).trim(), qualification: req.body.qualification || null, specialization: req.body.specialization || null, hospital: req.body.hospital || null, phone: req.body.phone || null, email: req.body.email || null, address: req.body.address || null, commission_percent: toNumber(req.body.commission_percent, existing.commission_percent), notes: req.body.notes || null, is_active: toBool(req.body.is_active, !!existing.is_active) ? 1 : 0, updated_at: now() }; await update('doctors', { id }, { $set: value }); await recordAudit({ req, action: 'update', module: 'doctors', entity: 'doctor', entityId: id, description: `Updated doctor "${value.name}"` }); res.json({ data: await enrich(await findOne('doctors', { id })) }); }));
router.delete('/:id', requirePermission('doctors.delete'), asyncHandler(async (req, res) => { const id = Number(req.params.id); const doctor = await findOne('doctors', { id }); if (!doctor) throw ApiError.notFound('Doctor not found'); if (await count('patients', { referred_by: id })) throw ApiError.conflict('This doctor is linked to patient records. Deactivate them instead of deleting.'); const { collections } = await appStore(); await collections.doctors.deleteOne({ id }); await recordAudit({ req, action: 'delete', module: 'doctors', entity: 'doctor', entityId: id, description: `Deleted doctor "${doctor.name}"` }); res.json({ message: 'Doctor deleted' }); }));
export default router;
