import express from 'express';
import { authenticate, requirePermission } from '../middleware/auth.js';
import { asyncHandler } from '../utils/errors.js';
import { appStore } from '../db/app-store.js';
import { formatDate } from '../utils/ids.js';
import { getSettings } from '../utils/settings.js';
const router = express.Router(); router.use(authenticate); const round = (v) => Math.round(Number(v || 0) * 100) / 100;
export function resolveRange(query) { const n = new Date(); const to = query.to || formatDate(n); let from = query.from; if (!from) { if (query.range === 'week') { const d = new Date(n); d.setDate(d.getDate() - ((d.getDay() + 6) % 7)); from = formatDate(d); } else if (query.range === 'month') from = formatDate(new Date(n.getFullYear(), n.getMonth(), 1)); else if (query.range === 'quarter') from = formatDate(new Date(n.getFullYear(), Math.floor(n.getMonth() / 3) * 3, 1)); else if (query.range === 'year') from = formatDate(new Date(n.getFullYear(), 0, 1)); else from = formatDate(n); } return { from, to }; }
function between(value, range) { const day = String(value || '').slice(0, 10); return day >= range.from && day <= range.to; }
async function summary(range) { const { collections } = await appStore(); const [payments, receipts, orders, items, tests, doctors] = await Promise.all([collections.payments.find({ is_void: 0 }).toArray(), collections.receipts.find({ status: 'active' }).toArray(), collections.orders.find({ is_deleted: 0 }).toArray(), collections.order_items.find({}).toArray(), collections.tests.find({}).toArray(), collections.doctors.find({}).toArray()]); const ps = payments.filter((p) => between(p.paid_at, range)); const rs = receipts.filter((r) => between(r.created_at, range)); const os = orders.filter((o) => between(o.created_at, range)); const is = items.filter((i) => os.some((o) => o.id === i.order_id)); const byMethod = [...new Set(ps.map((p) => p.method))].map((method) => ({ method, count: ps.filter((p) => p.method === method).length, amount: round(ps.filter((p) => p.method === method).reduce((s, p) => s + Number(p.amount || 0), 0)) })).sort((a, b) => b.amount - a.amount); const byDay = [...new Set(ps.map((p) => String(p.paid_at).slice(0, 10)))].sort().map((day) => ({ day, count: ps.filter((p) => String(p.paid_at).startsWith(day)).length, amount: round(ps.filter((p) => String(p.paid_at).startsWith(day)).reduce((s, p) => s + Number(p.amount || 0), 0)) })); const byDoctor = [...new Set(os.map((o) => o.doctor_id || 0))].map((id) => ({ doctor: doctors.find((d) => d.id === id)?.name || 'Walk-in', orders: os.filter((o) => (o.doctor_id || 0) === id).length, amount: round(os.filter((o) => (o.doctor_id || 0) === id).reduce((s, o) => s + Number(o.total || 0), 0)) })).sort((a, b) => b.amount - a.amount).slice(0, 10); const top = [...new Set(is.map((i) => i.test_name))].map((test_name) => ({ test_name, count: is.filter((i) => i.test_name === test_name).length, amount: round(is.filter((i) => i.test_name === test_name).reduce((s, i) => s + Number(i.price || 0) - Number(i.discount || 0), 0)) })).sort((a, b) => b.count - a.count || b.amount - a.amount).slice(0, 10); return { range, totals: { collected: round(ps.reduce((s, p) => s + Number(p.amount || 0), 0)), billed: round(os.reduce((s, o) => s + Number(o.total || 0), 0)), outstanding: round(os.reduce((s, o) => s + Number(o.balance || 0), 0)), receipts: rs.length, receipt_total: round(rs.reduce((s, r) => s + Number(r.amount_paid || 0), 0)), orders: os.length, tests: is.length, unpaid_orders: os.filter((o) => o.payment_status === 'unpaid').length, partial_orders: os.filter((o) => o.payment_status === 'partial').length, average_order_value: os.length ? round(os.reduce((s, o) => s + Number(o.total || 0), 0) / os.length) : 0 }, by_method: byMethod, by_day: byDay, by_category: [], by_doctor: byDoctor, top_tests: top }; }
router.get('/summary', requirePermission('revenue.view'), asyncHandler(async (req, res) => { const range = resolveRange(req.query); const settings = await getSettings(); const data = await summary(range); res.json({ data: { ...data, range: { ...range, preset: req.query.range || 'today' }, currency: { symbol: settings.currency_symbol, code: settings.currency_code, position: settings.currency_position } } }); }));
router.get('/overview', requirePermission('revenue.view'), asyncHandler(async (req, res) => { const data = {}; for (const preset of ['today', 'week', 'month', 'year']) { const result = await summary(resolveRange({ range: preset })); data[preset] = { range: result.range, collected: result.totals.collected, billed: result.totals.billed, orders: result.totals.orders }; } res.json({ data }); }));
router.get('/export', requirePermission('revenue.export'), asyncHandler(async (req, res) => { const range = resolveRange(req.query); const { collections } = await appStore(); const rows = await collections.payments.find({ is_void: 0 }).sort({ paid_at: 1 }).toArray(); const orders = new Map((await collections.orders.find({}).toArray()).map((o) => [o.id, o])); const patients = new Map((await collections.patients.find({}).toArray()).map((p) => [p.id, p])); const header = ['Date', 'Receipt No', 'Order No', 'Patient ID', 'Patient', 'Doctor', 'Amount', 'Method', 'Reference', 'Received By']; const escape = (v) => { const s = v == null ? '' : String(v); return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s; }; const csv = [header.join(','), ...rows.filter((p) => between(p.paid_at, range)).map((p) => [p.paid_at, '', orders.get(p.order_id)?.order_no, patients.get(p.patient_id)?.patient_code, patients.get(p.patient_id)?.full_name, '', p.amount, p.method, p.reference_no, ''].map(escape).join(','))].join('\n'); res.setHeader('Content-Type', 'text/csv; charset=utf-8'); res.setHeader('Content-Disposition', `attachment; filename="revenue_${range.from}_to_${range.to}.csv"`); res.send(csv); }));
export default router;
