import express from 'express';
import { authenticate, requirePermission } from '../middleware/auth.js';
import { asyncHandler, ApiError } from '../utils/errors.js';
import { recordAudit } from '../utils/audit.js';
import { now } from '../utils/ids.js';
import { appStore, findOne, insert, regex, update, count } from '../db/app-store.js';
import { requireFields, toBool, toNumber, toInt, paginate } from '../utils/validate.js';
const router = express.Router(); router.use(authenticate);
async function enrich(test) { if (!test) return null; const category = test.category_id ? await findOne('test_categories', { id: Number(test.category_id) }) : null; return { ...test, category_name: category?.name ?? null, category_color: category?.color ?? null }; }
router.get('/categories', requirePermission('tests.view'), asyncHandler(async (req, res) => { const { collections } = await appStore(); const rows = await collections.test_categories.find({}).sort({ sort_order: 1, name: 1 }).toArray(); const tests = await collections.tests.find({}).toArray(); res.json({ data: rows.map((row) => ({ ...row, test_count: tests.filter((test) => test.category_id === row.id).length })) }); }));
router.post('/categories', requirePermission('tests.create'), asyncHandler(async (req, res) => { requireFields(req.body, ['name']); const category = await insert('test_categories', { name: String(req.body.name).trim(), description: req.body.description || null, color: req.body.color || null, sort_order: toInt(req.body.sort_order, 0), is_active: toBool(req.body.is_active, true) ? 1 : 0, created_at: now(), updated_at: now() }); await recordAudit({ req, action: 'create', module: 'tests', entity: 'test_category', entityId: category.id, description: `Created test category "${category.name}"` }); res.status(201).json({ data: category }); }));
router.put('/categories/:id', requirePermission('tests.edit'), asyncHandler(async (req, res) => { const id = Number(req.params.id); const old = await findOne('test_categories', { id }); if (!old) throw ApiError.notFound('Test category not found'); requireFields(req.body, ['name']); const value = { name: String(req.body.name).trim(), description: req.body.description || null, color: req.body.color || null, sort_order: toInt(req.body.sort_order, old.sort_order), is_active: toBool(req.body.is_active, !!old.is_active) ? 1 : 0, updated_at: now() }; await update('test_categories', { id }, { $set: value }); await recordAudit({ req, action: 'update', module: 'tests', entity: 'test_category', entityId: id, description: `Updated test category "${value.name}"` }); res.json({ data: await findOne('test_categories', { id }) }); }));
router.delete('/categories/:id', requirePermission('tests.delete'), asyncHandler(async (req, res) => { const id = Number(req.params.id); const category = await findOne('test_categories', { id }); if (!category) throw ApiError.notFound('Test category not found'); if (await count('tests', { category_id: id })) throw ApiError.conflict('Move or delete the tests in this category first'); const { collections } = await appStore(); await collections.test_categories.deleteOne({ id }); await recordAudit({ req, action: 'delete', module: 'tests', entity: 'test_category', entityId: id, description: `Deleted test category "${category.name}"` }); res.json({ message: 'Category deleted' }); }));
router.get('/options', requirePermission('tests.view', 'orders.view', 'orders.create'), asyncHandler(async (req, res) => { const { collections } = await appStore(); const rows = await collections.tests.find({ is_active: 1 }).sort({ name: 1 }).toArray(); res.json({ data: await Promise.all(rows.map(enrich)) }); }));
router.get('/', requirePermission('tests.view'), asyncHandler(async (req, res) => { const { page, limit, offset } = paginate(req.query); const filter = {}; if (req.query.category_id) filter.category_id = Number(req.query.category_id); if (req.query.active === 'true') filter.is_active = 1; if (req.query.active === 'false') filter.is_active = 0; if (req.query.search) { const r = regex(req.query.search); filter.$or = [{ name: r }, { code: r }, { reference_range: r }]; } const { collections } = await appStore(); const total = await collections.tests.countDocuments(filter); const rows = await collections.tests.find(filter).sort({ name: 1 }).skip(offset).limit(limit).toArray(); res.json({ data: await Promise.all(rows.map(enrich)), meta: { total, page, limit, pages: Math.ceil(total / limit) || 1 } }); }));
router.get('/:id', requirePermission('tests.view'), asyncHandler(async (req, res) => { const test = await enrich(await findOne('tests', { id: Number(req.params.id) })); if (!test) throw ApiError.notFound('Test not found'); const { collections } = await appStore(); const ranges = await collections.test_reference_ranges.find({ test_id: test.id }).sort({ gender: 1, min_age: 1 }).toArray(); res.json({ data: { ...test, reference_ranges: ranges } }); }));
function payload(body, old = {}) { return { code: String(body.code ?? old.code ?? '').trim().toUpperCase(), name: String(body.name ?? old.name ?? '').trim(), category_id: body.category_id ?? old.category_id ?? null, price: toNumber(body.price, old.price ?? 0), cost: toNumber(body.cost, old.cost ?? 0), sample_type: body.sample_type ?? old.sample_type ?? null, unit: body.unit ?? old.unit ?? null, reference_range: body.reference_range ?? old.reference_range ?? null, method: body.method ?? old.method ?? null, turnaround_hours: toInt(body.turnaround_hours, old.turnaround_hours ?? 24), is_active: toBool(body.is_active, old.is_active === undefined ? true : !!old.is_active) ? 1 : 0 }; }
router.post('/', requirePermission('tests.create'), asyncHandler(async (req, res) => { requireFields(req.body, ['code', 'name']); const value = payload(req.body); if (await findOne('tests', { code: value.code })) throw ApiError.conflict('A test with that code already exists'); const test = await insert('tests', { ...value, created_at: now(), updated_at: now() }); await recordAudit({ req, action: 'create', module: 'tests', entity: 'test', entityId: test.id, description: `Created test "${test.name}" (${test.code})` }); res.status(201).json({ data: await enrich(test) }); }));
router.put('/:id', requirePermission('tests.edit'), asyncHandler(async (req, res) => { const id = Number(req.params.id); const old = await findOne('tests', { id }); if (!old) throw ApiError.notFound('Test not found'); requireFields(req.body, ['name']); const value = payload(req.body, old); const clash = await appStore().then(({ collections }) => collections.tests.findOne({ code: value.code, id: { $ne: id } })); if (clash) throw ApiError.conflict('Another test already uses that code'); await update('tests', { id }, { $set: { ...value, updated_at: now() } }); await recordAudit({ req, action: 'update', module: 'tests', entity: 'test', entityId: id, description: `Updated test "${value.name}"` }); res.json({ data: await enrich(await findOne('tests', { id })) }); }));
router.delete('/:id', requirePermission('tests.delete'), asyncHandler(async (req, res) => { const id = Number(req.params.id); const test = await findOne('tests', { id }); if (!test) throw ApiError.notFound('Test not found'); if (await count('order_items', { test_id: id })) throw ApiError.conflict('This test is used by existing orders. Deactivate it instead.'); const { collections } = await appStore(); await collections.tests.deleteOne({ id }); await recordAudit({ req, action: 'delete', module: 'tests', entity: 'test', entityId: id, description: `Deleted test "${test.name}" (${test.code})` }); res.json({ message: 'Test deleted' }); }));
export default router;
